### ISSUE TITLE
Unable to build x2 missing dependencies

### ISSUE THREAD

**Issue by ryan-sheldrake** [sonatype-nexus-community/nexus-repository-apt#3] opened 2017-01-13 07:50 UTC
Hi, 

This plugin sounds really good! I'd love to try it out. 

Upon trying to build, it fails with the below. 

[WARNING] The POM for bitwalker:UserAgentUtils:jar:1.12 is missing, no dependency information available
[WARNING] The POM for com.softwarementors.extjs:directjngine:jar:2.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

There seems to be a newer verison of UserAgentUtils which is fine. The directjengine.jar seems to have vanished. 

I don't know how critical these are to the plugin but would you mind taking a look? 

Thanks 

Ryan

**Comment by DarthHater** [comment] 2017-02-24 04:44
@ryan-sheldrake I am unable to reproduce this, maybe we can take a look together?

**Comment by mpoindexter** [comment] 2017-03-31 14:41
This also doesn't happen for me.   Maybe it was a problem with the old nexus dependencies in the pom,  going to close this, but feel free to reopen with more info if you're still having trouble.

**Closed as completed** 2017-03-31 14:42 UTC
